language: node_js
node_js:
  - "7"
before_script:
  - npm install
script: npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: node scripts/deploy.js $FTP_HOST $FTP_USER $FTP_PASSWORD
    on:
      branch: master