language: node_js
node_js:
  - "7"
before_script:
  - npm install
script: npm run build
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name $GITHUB_USER
      - git config --local user.email $GITHUB_MAIL
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  - provider: script
    skip_cleanup: true
    script: node scripts/deploy.js $FTP_HOST $FTP_USER $FTP_PASSWORD
    on:
      branch: master
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_OAUTH
    file: dist/index.html
    on:
      branch: master