language: node_js
node_js:
  - "7"
env:
  - MAJOR_VERSION=0
before_script:
  - npm install
script: npm run build
after_success:
  # Set up git user name and tag this commit
  - git config --local user.name $GITHUB_USER
  - git config --local user.email $GITHUB_MAIL
  - git tag "$MAJOR_VERSION.$TRAVIS_BUILD_NUMBER"
  - echo "$MAJOR_VERSION.$TRAVIS_BUILD_NUMBER"
deploy:
  - provider: script
    skip_cleanup: true
    script: node scripts/deploy.js $FTP_HOST $FTP_USER $FTP_PASSWORD
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: node scripts/deploy.js $FTP_HOST $FTP_USER_SANDBOX $FTP_PASSWORD_SANDBOX
    on:
      branch: casfee
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_OAUTH
    file_glob: true
    file: dist/*
    on:
      branch: master
